### ISSUE TITLE
Error trying to start the federation

### ISSUE THREAD

**Issue by dimm0** [admiraltyio/multicluster-scheduler#1]
```
(⎈ |nautilus:myazdani)➜  ~ kubectl apply -f  https://github.com/admiraltyio/multicluster-scheduler/releases/download/v0.2.0/scheduler.yaml

namespace/multicluster-scheduler created
```

`error: error validating "https://github.com/admiraltyio/multicluster-scheduler/releases/download/v0.2.0/scheduler.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false`

k8s v1.13.3

**Comment by adrienjt** [comment]
Thanks @dimm0 for giving multicluster-scheduler a try! I had fixed that issue on my side, just hadn't pushed to origin. Are you able to edit the scheduler.yaml and agent.yaml as in 89e7ac7, or would you rather me cut a 0.2.1 release with the fix in it? (I was sort of planning to include the fix in 0.3.0 with Cilium integration.)

**Comment by dimm0** [comment]
I'll fix those myself and let you know
Thanks!

**Comment by adrienjt** [comment]
@dimm0 The fix has been included in the latest release's manifest. FYI, [v0.3](https://github.com/admiraltyio/multicluster-scheduler/releases/tag/v0.3.0) also adds cross-cluster networking with Cilium.

**Comment by dimm0** [comment]
Awesome, thanks! I'll get back to it soon
