### ISSUE TITLE
Unable to delete resource objects after uninstallation

### ISSUE THREAD

**Issue by adrienjt** [admiraltyio/multicluster-scheduler#13]
Multicluster-scheduler adds finalizers to resources that it doesn't own, for proper garbage collection of remote observation objects. They must be removed when multicluster-scheduler is uninstalled. Otherwise, those objects cannot be deleted.

This should be implemented as a job run as a Helm post-uninstall hook.

In the meantime, you can run the following to properly clean up your system:

```bash
echo 'metadata:
  $deleteFromPrimitiveList/finalizers:
    - multicluster.admiralty.io/multiclusterForegroundDeletion' > patch.yaml

for kind in service pod persistentvolumeclaim replicationcontroller replicaset statefulset poddisruptionbudget
do
  kubectl get $kind --all-namespaces -o go-template='{{range .items}}{{ printf "kubectl patch %s %s -n %s -p \"$(cat patch.yaml)\"\n" .kind .metadata.name .metadata.namespace }}{{ end }}' | sh
done

for kind in node persistentvolume storageclass
do
  kubectl get $kind -o go-template='{{range .items}}{{ printf "kubectl patch %s %s -p \"$(cat patch.yaml)\"\n" .kind .metadata.name }}{{ end }}' | sh
done
```

**Comment by michael-db** [comment]
Just to note: Helm (as of now, v3.1.0) supports post-install hooks, but not post-uninstall hooks.
