### ISSUE TITLE
Helm setup requires two passes

### ISSUE THREAD

**Issue by danikam** [admiraltyio/multicluster-scheduler#15]
I'm finding that the helm setup used for the latest release (v0.6.0) takes two passes of the `helm install multicluster-scheduler [...]` to work properly. On the first pass of eg. 

```bash
helm install multicluster-scheduler admiralty/multicluster-scheduler \
  --kube-context $CLUSTER2 \
  --set agent.enabled=true \
  --set agent.clusterName=c2
```

the following error message is received:

```bash
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.233.54.131:443: connect: connection refused
```

and the `multicluster-scheduler-agent-[...]` pod is stuck in ContainerCreating state with the following  error, even after exporting the `remote` secret over via `./kubemcsa export --context $CLUSTER1 c1 --as remote | kubectl --context $CLUSTER1 apply -f -` and `./kubemcsa export --context $CLUSTER1 c2 --as remote | kubectl --context $CLUSTER2 apply -f -`:

```bash
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    3m7s                  default-scheduler  Successfully assigned default/multicluster-scheduler-agent-9fddf8bf-85ddk to node3
  Warning  FailedMount  2m59s (x5 over 3m7s)  kubelet, node3     MountVolume.SetUp failed for volume "remote" : secret "remote" not found
  Warning  FailedMount  64s                   kubelet, node3     Unable to mount volumes for pod "multicluster-scheduler-agent-9fddf8bf-85ddk_default(4160c035-35ec-11ea-a853-fa163ec400e7)": timeout expired waiting for volumes to attach or mount for pod "default"/"multicluster-scheduler-agent-9fddf8bf-85ddk". list of unmounted volumes=[cert]. list of unattached volumes=[cert config remote multicluster-scheduler-agent-token-6hpw8]
  Warning  FailedMount  59s (x9 over 3m7s)    kubelet, node3     MountVolume.SetUp failed for volume "cert" : secret "multicluster-scheduler-agent-cert" not found
```

Things seem to work fine after this point only after `multicluster-scheduler` is uninstalled and subsequently re-installed with helm:

```bash
helm uninstall multicluster-scheduler --kube-context cluster2
helm install multicluster-scheduler admiralty/multicluster-scheduler \
  --kube-context $CLUSTER2 \
  --set agent.enabled=true \
  --set agent.clusterName=c2
```

**Comment by skalp** [comment]
Hello, 
you should not get this problem if you install cert manager first:

**Comment by danikam** [comment]
Thanks for your reply @skalp! Ah, ok - so maybe I was just being a bit too hasty :) Will try again with some small test clusters, and make sure to check if cert-manager-webhook is running before doing the helm install.
