### ISSUE TITLE
fail to schedule pending pods

### ISSUE THREAD

**Issue by XiangLi0619** [admiraltyio/multicluster-scheduler#51]
I'm trying to write my own scheduler with kubernetes client python to schedule the pod. These pod are already submitted to the cluster and select my own scheduler. So they are pending in the clsuter. I patch annotation

 `{"multicluster.admiraly.io/clustername":str_cluster,'multicluster.admiralty.io/elect':''}`

to the pod and expect the pod is scheduled to <str_cluster>. But it failed to schedule. 

Then I check the pod yaml (not complete).
![image](https://user-images.githubusercontent.com/37281071/88187875-aa5bd980-cc69-11ea-9ab6-2a4bb64cbac0.png)

The result of `kubectl describe pod nginx-4` is
![image](https://user-images.githubusercontent.com/37281071/88188323-471e7700-cc6a-11ea-8494-7e4b705a9dae.png)
But the pod status is still pending, and the virtual pod does't appear.

Is multicluster-scheduler able to schedule the pending pod? How can I do with it?
Thanks.

**Comment by adrienjt** [comment]
1) What version of multicluster-scheduler are you running? Since v0.8,
  > You can no longer enforce placement with the `multicluster.admiralty.io/clustername` annotation. Use a more idiomatic node selector instead. (cf. [changelog](https://github.com/admiraltyio/multicluster-scheduler/blob/master/CHANGELOG.md#breaking-changes-1))
2) Is the namespace labeled with `multicluster-scheduler=enabled`? I don't see a `multicluster.admiralty.io/sourcepod-manifest` annotation on the pod, so it looks like the answer is no.
3) The event that you see is confusing, I agree. It's recorded by the feedback controller, which didn't do anything because it has nothing to do yet (as long as there's no delegate pod), so should just stay quiet.
4) Multicluster-scheduler uses its own schedulers (proxy scheduler on the source cluster side and candidate scheduler on the target cluster side), so it doesn't support third-party schedulers at the moment, but it's certainly possible with a light fork (of one component), or maybe a scheduler configuration tweak + webhook.

**Comment by XiangLi0619** [comment]
> 1. What version of multicluster-scheduler are you running? Since v0.8,
> 
> > You can no longer enforce placement with the `multicluster.admiralty.io/clustername` annotation. Use a more idiomatic node selector instead. (cf. [changelog](https://github.com/admiraltyio/multicluster-scheduler/blob/master/CHANGELOG.md#breaking-changes-1))
> 
> 1. Is the namespace labeled with `multicluster-scheduler=enabled`? I don't see a `multicluster.admiralty.io/sourcepod-manifest` annotation on the pod, so it looks like the answer is no.
> 2. The event that you see is confusing, I agree. It's recorded by the feedback controller, which didn't do anything because it has nothing to do yet (as long as there's no delegate pod), so should just stay quiet.
> 3. Multicluster-scheduler uses its own schedulers (proxy scheduler on the source cluster side and candidate scheduler on the target cluster side), so it doesn't support third-party schedulers at the moment, but it's certainly possible with a light fork (of one component), or maybe a scheduler configuration tweak + webhook, or pseudo-schedule at admission.

Thanks for your reply. I'm running v0.10.0-rc.1 in my clusters. It is still possible to enforce placement using "clustername" annotation in this version. I change to use the node selector. But there is one thing I still don't understand. If my scheduler just chooses the cluster for pods meanwhile another NOT DEFAULT scheduler in certain cluster make the node-level placement decisions,  how can I use the nodeSelector? By giving all the nodes in a cluster the same label?

**Comment by adrienjt** [comment]
> It is still possible to enforce placement using "clustername" annotation in this version.

No, it's not. I would know. The annotation doesn't even exist in the source code anymore. Do you have a broken install with old and new components?

> If my scheduler [...] meanwhile another NOT DEFAULT scheduler [...]

I repeat: multicluster-scheduler uses its own schedulers (proxy scheduler on the source cluster side and candidate scheduler on the target cluster side), so it doesn't support third-party schedulers.

Candidate pods are created by the proxy scheduler during its scheduling cycle; one of them becomes the actual delegate. So simply scheduling a pod to a virtual node using a different (your?) scheduler won't work. If you're interested in this feature, which is basically a bypass of most of multicluster-scheduler's functionality, please submit a separate issue with as much detail as possible about the use case.

> By giving all the nodes in a cluster the same label?

**IF** by "my scheduler" you mean multicluster-scheduler's proxy scheduler and by "another NOT DEFAULT scheduler" you mean multicluster-scheduler's candidate scheduler, then the answer is yes. Please refer to this doc section: https://github.com/admiraltyio/multicluster-scheduler/tree/v0.10.0-rc.1#advanced-scheduling 

There have been requests to use a node selector for the virtual nodes and another for the nodes in the target cluster. The same goes for other constraints. It's not clear how the user would specify two sets of scheduling constraints on the same source pod though, but UX suggestions are welcome.

**Comment by adrienjt** [comment]
Closing this issue as it's not actionable. @XiangLi0619, feel free to re-open if you have further questions.

The [Admiralty community chat](https://mattermost.admiralty.io/) is also a good place for questions.
