### ISSUE TITLE
Agent not working after fresh install on EKS 

### ISSUE THREAD

**Issue by Erik-Securenative** [admiraltyio/multicluster-scheduler#9]
agent logs show 
Federation namespace: multifederation
controller.go:160: cannot update *v1alpha1.NodePoolObservation eks-cluster-default in namespace multifederation in scheduler cluster: Operation cannot be fulfilled on nodepoolobservations.multicluster.admiralty.io "eks-cluster-default": the object has been modified; please apply your changes to the latest version and try again
controller.go:161: Could not reconcile Request. Stop working.

**Comment by adrienjt** [comment]
Hi Erik, thanks for trying multicluster-scheduler. The log you posted doesn't necessarily mean that the agent is not working. It's a common transient error when objects are updated concurrently, using optimistic concurrency: the controller doesn't get the latest object before updating it; if the object has changed since it was cached, the update fails, but the update is retried and eventually succeeds. That being said, we could use better logging around this to avoid confusion.

What else isn't working?

**Comment by Erik-Securenative** [comment]
The basic i tad argo workflow to run on cluster B and its running on cluster A

**Comment by skalp** [comment]
Hello,
I get the same issue.
First thing I misunderstood (might be obvious for other people) is that the scheduler doesn't "spawn" pods by itself, but delegates this to an agent. That means that if you want to schedule a pod in a cluster where the scheduler is deployed, you also need to deploy an agent in the exact same cluster.
You will also get a service account import issue if you try so schedule a workload on a agent living on the same cluster than the scheduler. The scheduler needs a service account import to reach its collocated agent, event if they live on the same cluster (and could theoretically directly use the proper service account to hit the api-server).
So something like this:
kubemcsa bootstrap --target-context cluster1 --source-context cluster1
must be done to schedule a workload from cluster2 (with agent deployed) in cluster1 (with agent + scheduler).
Once done, everything ran fine on my side.
If the pod is still scheduled on the wrong cluster, you could eventually add few logs, and check what's going on here
https://github.com/admiraltyio/multicluster-scheduler/blob/master/pkg/scheduler/basic.go#L85

**Comment by adrienjt** [comment]
Thank you @skalp, everything you wrote is correct, and great material to clarify the documentation :)
